/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package museumkiosk;

import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author karis
 */
public class MuseumPage extends javax.swing.JFrame {

    
     ButtonGroup quiz1=new ButtonGroup();
     ButtonGroup quiz2=new ButtonGroup();
     ButtonGroup quiz3=new ButtonGroup();
     ButtonGroup quiz4=new ButtonGroup();
     ButtonGroup quiz5=new ButtonGroup();
     ButtonGroup quiz6=new ButtonGroup();
    /**
     * Creates new form MuseumPage
     */
    public MuseumPage() {
        initComponents();
        
        indexLocal();//call the method to determine the index page
      
        
        
    //Button Group for Quiz1
   
    quiz1.add(jRq1a);
    quiz1.add(jRq1b);
    quiz1.add(jRq1c);
    
       
    //Button Group for Quiz2
    quiz2.add(jRq2a);
    quiz2.add(jRq2b);
    quiz2.add(jRq2c);
    
       
    //Button Group for Quiz3
    quiz3.add(jRq3a);
    quiz3.add(jRq3b);
    quiz3.add(jRq3c);
    
       
    //Button Group for Quiz4
    quiz4.add(jRq4a);
    quiz4.add(jRq4b);
    quiz4.add(jRq4c);
    
       
    //Button Group for Quiz5
    quiz5.add(jRq4a);
    quiz5.add(jRq4b);
    quiz5.add(jRq4c);
    
    //Button Group for Quiz6
    quiz6.add(jRq6a);
    quiz6.add(jRq6b);
    quiz6.add(jRq6c);
    
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jRq1a = new javax.swing.JRadioButton();
        jRq1b = new javax.swing.JRadioButton();
        jRq1c = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jRq2b = new javax.swing.JRadioButton();
        jRq2a = new javax.swing.JRadioButton();
        jRq2c = new javax.swing.JRadioButton();
        jRq3a = new javax.swing.JRadioButton();
        jRq3c = new javax.swing.JRadioButton();
        jRq3b = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jRq6a = new javax.swing.JRadioButton();
        jRq6c = new javax.swing.JRadioButton();
        jRq6b = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jRq4a = new javax.swing.JRadioButton();
        jRq4b = new javax.swing.JRadioButton();
        jRq4c = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jRq5a = new javax.swing.JRadioButton();
        jRq5c = new javax.swing.JRadioButton();
        jRq5b = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jBprevious = new javax.swing.JButton();
        jBnext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel1.setFont(new java.awt.Font("eufm10", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Endangered Animal Species");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/index.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jTextArea2.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("The body length is 2 to 3.5 m (6 ft \n7 in to 11 ft 6 in) for adults 1 m \n(3 ft 3 in) for infants. An adult \nweighs 150 to 230 kg (330 to 510 \nlb). Indo-Pacific humpback dolphins \nlive up to 40 years, as determined\n by the analysis of their teeth.\n\nAt birth, the dolphins are black.\n They change to grey, then pinkish \nwith spots when young. Adults are \ngray, white or pink. ");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setFont(new java.awt.Font("eufm10", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setText("Chinese White Dolphine  Description");

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("The Indo-Pacific humpback dolphin (Sousa chinensis;\n Chinese: pinyin: Zhōnghuá bái hǎitún)is a species of \nhumpback dolphin inhabiting coastal waters of the \neastern Indian and western Pacific  Oceans.\n\n This species is often referred to Chinese \nwhite dolphins in China (including Hong Kong, Macao\n and Taiwan) and Singapore as common name. Some\n biologists regard the Indo-Pacific dolphin as a\n subspecies of the Indian Ocean humpback dolphin \nwhich ranges from east Africa to India.\n\nAn adult Indo-Pacific humpback dolphin is gray, white\nor pink and may appear as an albino dolphin to\nsome. Uniquely, the population along the Chinese \ncoast has pink skin,\n");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel1);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("eufm10", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Behavior ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(160, 12, 279, 36);

        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("\nIndo-Pacific white dolphins come to the water\n surface to breathe for 20 to 30 seconds before \ndiving deep again, for two to eight minutes. Dolphin \ncalves, with smaller lung capacities, surface twice as \noften as adults, staying underwater for one to three \nminutes.\n\n Adult dolphins rarely stay under water for more\n than four minutes. They sometimes leap completely\n out of the water. They may also rise up vertically\n from the water, exposing the dorsal half of their \nbodies. A pair of protruding eyes allows them to \nsee clearly in both air and water. ");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(12, 54, 445, 294);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(6, 54, 0, 316);

        jTextArea5.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("\nIndo-Pacific white dolphins are sociable creatures and live in \ngroups of three to four. Female dolphins become mature at 10 years\nold, while the males become mature at 13 years old. They usually\nmate from the end of summer to autumn.\n\nInfant dolphins are usually born 11 months after the mating. Mature \nfemales can give birth every three years, and parental care lasts until\ntheir offspring can find food  themselves. ");
        jScrollPane5.setViewportView(jTextArea5);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(469, 260, 584, 224);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim2.gif"))); // NOI18N
        jPanel2.add(jLabel27);
        jLabel27.setBounds(0, 160, 560, 390);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim2.gif"))); // NOI18N
        jPanel2.add(jLabel28);
        jLabel28.setBounds(480, 160, 80, 390);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim2.gif"))); // NOI18N
        jPanel2.add(jLabel29);
        jLabel29.setBounds(560, -10, 480, 390);

        jTabbedPane1.addTab("", jPanel2);

        jLabel6.setFont(new java.awt.Font("eufm10", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("Human and The environment");

        jTextArea4.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("\nThe white  dolphin is threatened by both habitat loss and pollution.\n Conservationists warn that Hong Kong may lose its rare Indo-Pacific humpback \ndolphins, also known as pink dolphins for their unique colour, unless China takes \nurgent action against pollution and other threats. \n\nTheir numbers in Hong Kong waters have fallen from an estimated 158 in 2003 to\n just 78 in 2011, with a further decline expected by the Hong Kong Dolphin\n Conservation Society");
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea10.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextArea10.setRows(5);
        jTextArea10.setText("\nThe subject of plastic pollution is a global phenomenon that has no-end in sight. \nPlastic pollution is widespread across all entangling oceans due to their buoyant and\ndurable properties that allow for sorption of toxicants to plastic while traveling \nthrough the environment.\n\nThere are many transit paths that allow for plastics and pollutions to enter oceans. \nFreshwater waste can enter oceans by rivers; delta or estuary (where rivers meet \nthe ocean). Human populations discarding their waste directly into marine waters.");
        jScrollPane10.setViewportView(jTextArea10);

        jLabel9.setFont(new java.awt.Font("eufm10", 1, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 0));
        jLabel9.setText("Impact of Plastic Polution");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1.jpeg"))); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim3.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel3);

        jLabel13.setFont(new java.awt.Font("eufm10", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Pollutants");

        jTextArea11.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextArea11.setRows(5);
        jTextArea11.setText("Indo-Pacific humpback dolphin (Sousa chinensis) are chronically \nexposed to organic pollutants since they inhabit shallow coastal \nwaters that are often impacted by anthropogenic activities. \n\nAnthropogenic pollutants pose a risk to marine mammals that \nreside in coastal waters. Discharge of organic pollutants into \nmarine environments has been shown to decrease water quality \nresulting in loss of habitats and a significant reduction in the\n species richness.\n\nThe loss of key pods have caused specie fragmentation, also due \nto habitat loss, which inclines specie isolation; decrease connectivity\nresulting in population decline. This loss in population is what lead \nthis species to be labeled as near threatened on the IUCN Red List \nof Threatened Species.\n\nThe consumption of plastics have adverse effects in marine\n mammals such as disease susceptibility, reproductive and \ndevelopmental toxicity.");
        jScrollPane11.setViewportView(jTextArea11);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim1.gif"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/3.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 146, Short.MAX_VALUE))
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel5);

        jPanel6.setLayout(null);

        jTextArea12.setBackground(new java.awt.Color(0, 204, 204));
        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextArea12.setRows(5);
        jTextArea12.setText("In Hong Kong, boat trips to visit the Indo-Pacific humpback \ndolphins have been running since the 1990s. The dolphins \nmainly live in the waters of Lantau North, Southeast Lantau, \nthe Soko Islands and Peng Chau. A code of conduct regulates\ndolphin-watching activity in Hong Kong waters.\n\nThere have been some reports of dolphin watching practices \nthat have further endangered the Indo-Pacific humpback \ndolphins, such as in Sanniang Bay dolphin sanctuary in \nQinzhou and off Xiamen.\n\nHowever, these generally are small, locally organised one-off \ntours or private pleasure boats that do not adhere to the Hong \nKong Agricultural and Fisheries Department's voluntary code of \nconduct");
        jScrollPane12.setViewportView(jTextArea12);

        jPanel6.add(jScrollPane12);
        jScrollPane12.setBounds(240, 70, 537, 323);

        jLabel14.setFont(new java.awt.Font("eufm10", 1, 32)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 153));
        jLabel14.setText("Distribution and Dolphine watching");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(54, 18, 572, 50);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim3.gif"))); // NOI18N
        jPanel6.add(jLabel22);
        jLabel22.setBounds(0, 70, 240, 320);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim3.gif"))); // NOI18N
        jPanel6.add(jLabel32);
        jLabel32.setBounds(780, 70, 240, 320);

        jTabbedPane1.addTab("", jPanel6);

        jLabel7.setFont(new java.awt.Font("eufm10", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Chinese White Dolphin Interesting  Facts");

        jLabel8.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 255));
        jLabel8.setText("What Color?");

        jTextArea6.setBackground(new java.awt.Color(204, 204, 0));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("\nThough it is usually called Chinese white \ndolphin, it is not really WHITE. Chinese \nwhite dolphin is grey and spotty when it is\nyounger.\nIts spots would be faded and  colour would\nbe changed to pink when it grows older");
        jScrollPane6.setViewportView(jTextArea6);

        jLabel10.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 255));
        jLabel10.setText("Favourite Food");

        jTextArea7.setBackground(new java.awt.Color(204, 204, 0));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("\nFish, fish, fish and more fish. It is not so \nfussy about the type, feeding on at least \ntwenty different species including lion \nhead fish Collichthys lucida, various \ncroakers Johnius spp and anchovies \nThryssa spp.");
        jScrollPane7.setViewportView(jTextArea7);

        jLabel11.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 255));
        jLabel11.setText("How long does it live");

        jTextArea8.setBackground(new java.awt.Color(204, 204, 0));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("\nChinese white dolphin has a long life expectancy \nof up to 40 years, though in Hong Kong most\nChinese White Dolphins live into their  30s. \n\nScientists who study the dolphin are able to \nwork out its age by examining its teeth");
        jScrollPane8.setViewportView(jTextArea8);

        jLabel12.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 255));
        jLabel12.setText("Good Peer Support");

        jTextArea9.setBackground(new java.awt.Color(204, 204, 0));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("\nChinese white dolphin is a very sociable animal. \nIt usually spends time in small groups of about 4.\n\nThe baby calf learns a lot by playing with the \ngroup mates. By doing so, it can pick up the \nnecessary social skills for adulthood.");
        jScrollPane9.setViewportView(jTextArea9);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(228, 228, 228))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(115, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel7);

        jPanel9.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Padauk Book", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Review Questions");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(335, 12, 324, 44);

        jButton2.setFont(new java.awt.Font("eufm10", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);
        jButton2.setBounds(430, 500, 168, 44);

        jLabel15.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 0));
        jLabel15.setText("Q1: What is the Color of Chinese White Dolphine?");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(40, 80, 361, 45);

        jRq1a.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq1a.setForeground(new java.awt.Color(0, 0, 0));
        jRq1a.setText("Grey,Black or Pink");
        jPanel9.add(jRq1a);
        jRq1a.setBounds(30, 130, 187, 28);

        jRq1b.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq1b.setForeground(new java.awt.Color(0, 0, 0));
        jRq1b.setText("Grey, Pink or Brown");
        jPanel9.add(jRq1b);
        jRq1b.setBounds(250, 130, 220, 28);

        jRq1c.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq1c.setForeground(new java.awt.Color(0, 0, 0));
        jRq1c.setText("Grey, White or Pink");
        jPanel9.add(jRq1c);
        jRq1c.setBounds(30, 180, 187, 28);

        jLabel17.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 204, 0));
        jLabel17.setText("Q2: What is the body length of adult white Dolphine?");
        jPanel9.add(jLabel17);
        jLabel17.setBounds(40, 230, 407, 45);

        jRq2b.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq2b.setForeground(new java.awt.Color(0, 0, 0));
        jRq2b.setText("3 to 5mtrs");
        jPanel9.add(jRq2b);
        jRq2b.setBounds(230, 280, 150, 28);

        jRq2a.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq2a.setForeground(new java.awt.Color(0, 0, 0));
        jRq2a.setText("2 to 3.5 mtrs");
        jPanel9.add(jRq2a);
        jRq2a.setBounds(40, 280, 160, 28);

        jRq2c.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq2c.setForeground(new java.awt.Color(0, 0, 0));
        jRq2c.setText("2 to 4 mtrs");
        jPanel9.add(jRq2c);
        jRq2c.setBounds(40, 330, 160, 28);

        jRq3a.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq3a.setForeground(new java.awt.Color(0, 0, 0));
        jRq3a.setText("130 to 250kgs");
        jPanel9.add(jRq3a);
        jRq3a.setBounds(40, 420, 170, 28);

        jRq3c.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq3c.setForeground(new java.awt.Color(0, 0, 0));
        jRq3c.setText("200 to 330 kgs");
        jPanel9.add(jRq3c);
        jRq3c.setBounds(40, 460, 172, 28);

        jRq3b.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq3b.setForeground(new java.awt.Color(0, 0, 0));
        jRq3b.setText("150 to 230 kgs");
        jPanel9.add(jRq3b);
        jRq3b.setBounds(230, 420, 170, 28);

        jLabel18.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 0));
        jLabel18.setText("Q3: What is the weight of adult dolphine?");
        jPanel9.add(jLabel18);
        jLabel18.setBounds(40, 360, 361, 45);

        jRq6a.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq6a.setForeground(new java.awt.Color(0, 0, 0));
        jRq6a.setText("10 months");
        jPanel9.add(jRq6a);
        jRq6a.setBounds(520, 410, 140, 28);

        jRq6c.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq6c.setForeground(new java.awt.Color(0, 0, 0));
        jRq6c.setText("11 months");
        jPanel9.add(jRq6c);
        jRq6c.setBounds(520, 450, 140, 28);

        jRq6b.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq6b.setForeground(new java.awt.Color(0, 0, 0));
        jRq6b.setText("12 months");
        jPanel9.add(jRq6b);
        jRq6b.setBounds(690, 410, 160, 28);

        jLabel21.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 204, 0));
        jLabel21.setText("Q6: How long is the gestation period of white Dolphine? ");
        jPanel9.add(jLabel21);
        jLabel21.setBounds(520, 360, 361, 45);

        jRq4a.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq4a.setForeground(new java.awt.Color(0, 0, 0));
        jRq4a.setText("White");
        jPanel9.add(jRq4a);
        jRq4a.setBounds(510, 140, 98, 28);

        jRq4b.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        jRq4b.setForeground(new java.awt.Color(0, 0, 0));
        jRq4b.setText("Pink");
        jRq4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRq4bActionPerformed(evt);
            }
        });
        jPanel9.add(jRq4b);
        jRq4b.setBounds(720, 140, 130, 28);

        jRq4c.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq4c.setForeground(new java.awt.Color(0, 0, 0));
        jRq4c.setText("Black");
        jPanel9.add(jRq4c);
        jRq4c.setBounds(510, 190, 87, 28);

        jLabel19.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 0));
        jLabel19.setText("Q4: What is the color that the White dolphin are born in?");
        jPanel9.add(jLabel19);
        jLabel19.setBounds(510, 80, 361, 45);

        jLabel20.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 204, 0));
        jLabel20.setText("Q5: How long do white dolphine stay over water before they dive back?");
        jPanel9.add(jLabel20);
        jLabel20.setBounds(520, 230, 494, 45);

        jRq5a.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq5a.setForeground(new java.awt.Color(0, 0, 0));
        jRq5a.setText("20 to 30seconds");
        jPanel9.add(jRq5a);
        jRq5a.setBounds(510, 290, 180, 28);

        jRq5c.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq5c.setForeground(new java.awt.Color(0, 0, 0));
        jRq5c.setText("10 to 20 seconds");
        jRq5c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRq5cActionPerformed(evt);
            }
        });
        jPanel9.add(jRq5c);
        jRq5c.setBounds(510, 330, 180, 28);

        jRq5b.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        jRq5b.setForeground(new java.awt.Color(0, 0, 0));
        jRq5b.setText("30 to 40 seconds");
        jPanel9.add(jRq5b);
        jRq5b.setBounds(710, 290, 190, 28);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim1.gif"))); // NOI18N
        jPanel9.add(jLabel26);
        jLabel26.setBounds(630, 0, 430, 520);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim1.gif"))); // NOI18N
        jPanel9.add(jLabel30);
        jLabel30.setBounds(0, 0, 430, 520);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anim1.gif"))); // NOI18N
        jPanel9.add(jLabel31);
        jLabel31.setBounds(430, 0, 200, 520);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel4);

        jBprevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/previous.jpeg"))); // NOI18N
        jBprevious.setText("Previous");
        jBprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpreviousActionPerformed(evt);
            }
        });

        jBnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/next.jpeg"))); // NOI18N
        jBnext.setText("Next");
        jBnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(jBnext, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnext, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRq4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRq4bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRq4bActionPerformed

    private void jRq5cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRq5cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRq5cActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            QuestionsSubmit();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpreviousActionPerformed
                 
        
        //Call the previous method
           previousButton();

// TODO add your handling code here:
    }//GEN-LAST:event_jBpreviousActionPerformed

    private void jBnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnextActionPerformed
        //Call the next button
        nextButton();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuseumPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuseumPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuseumPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuseumPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuseumPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBnext;
    private javax.swing.JButton jBprevious;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRq1a;
    private javax.swing.JRadioButton jRq1b;
    private javax.swing.JRadioButton jRq1c;
    private javax.swing.JRadioButton jRq2a;
    private javax.swing.JRadioButton jRq2b;
    private javax.swing.JRadioButton jRq2c;
    private javax.swing.JRadioButton jRq3a;
    private javax.swing.JRadioButton jRq3b;
    private javax.swing.JRadioButton jRq3c;
    private javax.swing.JRadioButton jRq4a;
    private javax.swing.JRadioButton jRq4b;
    private javax.swing.JRadioButton jRq4c;
    private javax.swing.JRadioButton jRq5a;
    private javax.swing.JRadioButton jRq5b;
    private javax.swing.JRadioButton jRq5c;
    private javax.swing.JRadioButton jRq6a;
    private javax.swing.JRadioButton jRq6b;
    private javax.swing.JRadioButton jRq6c;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables

//Method for taking question answers
    public void QuestionsSubmit(){
       String Q1, Q2, Q3, Q4, Q5;
       String answers="";
       
       int marks=0, percentage=0;
       
       //if the correct question is selected for quiz 1
       if(jRq1c.isSelected()==true){
       marks+=1;
        } else {
       answers=answers+"\n Quiz 1: "+jRq1c.getText()+" ";
       }
       
       //if the correct question is selected for quiz 2
       if(jRq2a.isSelected()==true){
       marks=marks+1;
       JOptionPane.showMessageDialog(null, "kk 2 "+marks);
       }else{
       answers=answers+"\n Quiz 2: "+jRq2a.getText()+" ";
       }
       
       //if the correct question is selected for quiz 3
       if(jRq3b.isSelected()==true){
       marks=marks+1;
       }else{
       answers=answers+"\n Quiz 3: "+jRq3b.getText()+" ";
       }
       
       //if the correct question is selected for quiz 4
       if(jRq4c.isSelected()==true){
       marks=marks+1;
       }else{
       answers=answers+"\n Quiz 4: "+jRq4c.getText()+" ";
       }
       
       //if the correct question is selected for quiz 5       
       if(jRq5a.isSelected()==true){
       marks=marks+1;
       }else{
       answers=answers+"\n Quiz 5: "+jRq5a.getText()+" ";
       }
       
       //if the correct question is selected for quiz 5
       if(jRq6c.isSelected()==true){
       marks=marks+1;
       }else{ 
       answers=answers+"\n Quiz 6: "+jRq6c.getText()+" ";
       }
      
       //if the user has gotten all the questions correct congratulate them
       //else show them the correct question
       if(marks==6){     
       JOptionPane.showMessageDialog(null, "Congratulations Your score is "+marks+"/6");
       }else{
        JOptionPane.showMessageDialog(null, "Your score is "+marks+"/6"+"\n\n answers to the failed question is: \n"+answers);
       }
      
        
            
    
    }
    
//Method for button to navigate to the next tab
    public void nextButton(){
    //Navigate through the pages
        jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()+1); 
        indexLocal(); //call the method to determine the index page
    }
    //Method for button to navigate to the previous tab
    public void previousButton(){
    //Navigate through the pages
    indexLocal();//call the method to determine the index page    
    jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()-1); 
       // indexLocal();//call the method to determine the index page
    }
    //method to check if index of the page
    public void indexLocal(){
    //if the its the first page Disable the previous button
        if(jTabbedPane1.getSelectedIndex()==0){
        jBprevious.setEnabled(false);
        jBnext.setEnabled(true);
        }else
        //if the its the last page Disable the next button
        if(jTabbedPane1.getSelectedIndex()==6){
         jBnext.setEnabled(false);
         jBprevious.setEnabled(true);
        }else{
        jBnext.setEnabled(true);
         jBprevious.setEnabled(true);
        }
    
    }
    
}
